openapi: 3.0.3
info:
  title: Swiss Bitcoin Pay Merchant's API
  description: "API for merchants to connect to their Swiss Bitcoin Pay's wallet account.<br/>For creating an invoice, you need to provide the `api-key` header with your API Key, available in your dashboard (not required for reading invoice)."
  termsOfService: http://swagger.io/terms/
  contact:
    email: hello@swiss-bitcoin-pay.ch
  version: 1.1.3
servers:
  - url: https://api.swiss-bitcoin-pay.ch
tags:
  - name: checkout
    description: Everything about creating and checking invoices
paths:
  /checkout:
    post:
      tags:
        - checkout
      summary: Create an invoice
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CheckoutRequest"
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckoutResponse"
        "403":
          description: Api key not provided
        "500":
          description: Invalid API key or unknown error
  /checkout/{id}:
    get:
      tags:
        - checkout
      summary: Check invoice status
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Hash ID of invoice
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckoutStatus"
        "500":
          description: Unknown error
components:
  schemas:
    CheckoutRequest:
      required:
        - title
        - amount
      type: object
      properties:
        title:
          type: string
          description: "What will appear on the client's wallet"
        description:
          type: string
        amount:
          type: number
          description: "How much to charge, with decimals. ex: `21.50`"
        unit:
          default: Your account's default currency
          type: string
          description: "Optionally select a reference currency you want use. All major currencies are supported, along with `sat` and `BTC`"
        onChain:
          default: false
          type: boolean
          description: "If Onchain payment is available"
        delay:
          default: 10
          type: number
          description: "How long (in minutes) the client have to pay the invoice before it gets expired"
        email:
          type: string
          description: "An message containing the created invoice will be sent to this email"
        emailLanguage:
          type: string
          description: "In which language the email should be sent. Currently only supports `en` and `fr`"
        redirect:
          type: boolean
          description: "If the server should directly return a 302 REDIRECT request to force the user's browser to go to the invoice payment page"
        redirectAfterPaid:
          type: string
          description: "Where the user will be redirected after paid (confirmation page).<br/>(Lightning: instant, Onchain: after 1 confirmation)"
        webhook:
          type: string
          description: "Our backend will call this webhook with a POST request will all the invoice details once it has been paid<br/>(Lightning: instant, Onchain: after 1 confirmation)<br/><br/>This data is never visible to the user."
    CheckoutResponse:
      required:
        - id
        - pr
        - checkoutUrl
      type: object
      properties:
        id:
          type: string
        pr:
          type: string
        checkoutUrl:
          type: string
        onChainAddr:
          type: string
    CheckoutStatus:
      required:
        - createdAt
        - delay
        - pr
        - amount
        - btcAmount
        - unit
        - isPaid
        - isInit
        - isExpired
        - title
        - hash
        - fiatAmount
        - fiatUnit
      type: object
      properties:
        createdAt:
          type: number
        delay:
          type: number
        pr:
          type: string
        amount:
          type: number
        btcAmount:
          type: string
        unit:
          type: string
        isPaid:
          type: boolean
        isInit:
          type: boolean
        isExpired:
          type: boolean
        paymentMethid:
          type: string
          enum:
            - lightning
            - onchain
        paidAt:
          type: number
        title:
          type: string
        description:
          type: string
        hash:
          type: string
        fiatAmount:
          type: number
        fiatUnit:
          type: string
        onChainAddr:
          type: string
        minConfirmations:
          type: number
        confirmations:
          type: number
        txid:
          type: string
        idPending:
          type: boolean
        redirectAfterPaid:
          type: string
    Payment:
      type: object
      properties:
        checking_id:
          type: string
        pending:
          type: boolean
        amount:
          type: number
        fee:
          type: number
        memo:
          type: string
        time:
          type: number
        bolt11:
          type: string
        preimage:
          type: string
        payment_hash:
          type: string
        extra:
          type: object
        wallet_id:
          type: string
        webhook:
          type: string
        webhook_status:
          type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: "api-key"
